version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather-backend
    ports:
      - "8000:8000"
    networks:
      - weather-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
